version: "3"
virtualbrowsers:
- name: harness
  url: https://app.harness.io/ng/account/UL037itkT6SA3IDdIIXWcQ/main-dashboard
virtualmachines:
- name: sandbox
  image: instruqt/k3s-v1-29-0
  shell: /bin/bash
  machine_type: n2-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
secrets:
- name: SE_WORKSHOP_PAT
- name: SE_WORKSHOP_ORG_ID
- name: SE_WORKSHOP_ACCOUNT_ID
- name: SE_WORKSHOP_USER_PWD
- name: SE_WORKSHOP_USER_GRP_ID
- name: SE_WORKSHOP_KEYCLOAK_ENDPOINT
- name: SE_WORKSHOP_KEYCLOAK_REALM
- name: SE_WORKSHOP_KEYCLOAK_ADMIN_USER
- name: SE_WORKSHOP_KEYCLOAK_ADMIN_PWD
- name: SE_WORKSHOP_GKE_GENERATOR
- name: SE_WORKSHOP_GRAFANA_PW
