#!/usr/bin/env python3

import os
from pyharnessworkshop import harness, utils

# REQUIRED VARIABLES LIST
HARNESS_ACCOUNT_ID = os.getenv("SE_WORKSHOP_ACCOUNT_ID")
HARNESS_ORG_ID = os.getenv("SE_WORKSHOP_ORG_ID")
HARNESS_PAT = os.getenv("SE_WORKSHOP_PAT")
HARNESS_PROJECT = utils.instruqt.get_agent_variable("HARNESS_PRJ_ID")
CODE_REPO = utils.instruqt.get_agent_variable("HARNESS_REPO")

# Lab values
lab_id = "lab2"
default_pipeline_name = "Workshop Build and Deploy"
default_pipeline_id = "Workshop_Build_and_Deploy"
execution_notes = f"Automatically executed via Instruqt '{lab_id.title()}' Track Skip."
default_service_name = "frontend"
default_service_id = "frontend"

json_response = harness.platform.list_pipelines(HARNESS_PAT, HARNESS_ACCOUNT_ID, HARNESS_ORG_ID, HARNESS_PROJECT)
pipeline_data = harness.platform.get_pipeline_by_id(json_response, default_pipeline_id)

# Extract details or use default values
pipeline_name = pipeline_data.get("name", default_pipeline_name) if pipeline_data else default_pipeline_name
pipeline_id = pipeline_data.get("identifier", default_pipeline_id) if pipeline_data else default_pipeline_id

pipeline_context = {
    "pipeline_name": pipeline_name,
    "pipeline_id": pipeline_id,
    "project_id": HARNESS_PROJECT,
    "org_id": HARNESS_ORG_ID,
    "harness_repo": CODE_REPO
}

pipeline_yaml = utils.misc.render_template_from_url(pipeline_context, f"se-workshop-devsecops/assets/gar/yaml_spec/{lab_id}_pipeline.yaml.template")

if pipeline_data:
    print("Updating pipeline.")
    harness.platform.update_pipeline(HARNESS_PAT, HARNESS_ACCOUNT_ID, HARNESS_ORG_ID, HARNESS_PROJECT, pipeline_id, pipeline_yaml)
else:
    print("Pipeline not found. Creating a new pipeline.")
    harness.platform.create_harness_pipeline(HARNESS_PAT, HARNESS_ACCOUNT_ID, HARNESS_ORG_ID, HARNESS_PROJECT, pipeline_yaml)

# Configure Service
json_response = harness.platform.list_services(HARNESS_PAT, HARNESS_ACCOUNT_ID, HARNESS_ORG_ID, HARNESS_PROJECT)
service_data = harness.platform.get_service_by_id(json_response, default_service_id)

# Extract service details or use default values
service_name = service_data.get("name", default_service_name) if service_data else default_service_name
service_id = service_data.get("identifier", default_service_id) if service_data else default_service_id

service_context = {
    "service_name": service_name,
    "service_id": service_id,
    "project_id": HARNESS_PROJECT,
    "org_id": HARNESS_ORG_ID,
    "harness_repo": CODE_REPO
}

service_yaml = utils.misc.render_template_from_url(service_context, f"se-workshop-devsecops/assets/gar/yaml_spec/{lab_id}_service.yaml.template")
utils.misc.validate_yaml_content(service_yaml)
json_payload = {
    "identifier": f"{service_id}",
    "orgIdentifier": f"{HARNESS_ORG_ID}",
    "projectIdentifier": f"{HARNESS_PROJECT}",
    "yaml": f"{service_yaml}"
}

if service_data:
    print("Updating service.")
    harness.platform.update_service(HARNESS_PAT, HARNESS_ACCOUNT_ID, HARNESS_ORG_ID, HARNESS_PROJECT, service_id, json_payload)
else:
    print("Service not found. Creating a new service.")
    harness.platform.create_service(HARNESS_PAT, HARNESS_ACCOUNT_ID, HARNESS_ORG_ID, HARNESS_PROJECT, json_payload)

execution_yaml = f"""\
pipeline:
  identifier: {pipeline_id}
  properties:
    ci:
      codebase:
        build:
          spec:
            branch: main
          type: branch
"""

harness.platform.execute_pipeline(HARNESS_PAT, HARNESS_ACCOUNT_ID, HARNESS_ORG_ID, HARNESS_PROJECT, pipeline_id, execution_yaml, execution_notes)
