version: "3"
virtualbrowsers:
- name: harness
  url: https://app.harness.io/ng/account/UL037itkT6SA3IDdIIXWcQ/main-dashboard
- name: servicenow
  url: https://ven03172.service-now.com/now/nav/ui/classic/params/target/change_request_list.do%3Fsysparm_userpref_module%3Dcd579a82c0a8016400aa77d97a4d70a8%26sysparm_fixed_query%3Dopened_by%3Djavascript%3Ags.getUserID()
virtualmachines:
- name: sandbox
  image: sales-209522/harness-se-workshop-v0-0-15
  shell: /bin/bash
  machine_type: n2-standard-8
  allow_external_ingress:
  - http
  - https
  - high-ports
  provision_ssl_certificate: true
secrets:
- name: SE_WORKSHOP_PAT
- name: SE_WORKSHOP_ORG_ID
- name: SE_WORKSHOP_ACCOUNT_ID
- name: SE_WORKSHOP_USER_GRP_ID
- name: SE_WORKSHOP_KEYCLOAK_ENDPOINT
- name: SE_WORKSHOP_KEYCLOAK_REALM
- name: SE_WORKSHOP_KEYCLOAK_ADMIN_USER
- name: SE_WORKSHOP_KEYCLOAK_ADMIN_PWD
- name: SE_WORKSHOP_SN_INSTANCE
- name: SE_WORKSHOP_SN_ADMIN_USER
- name: SE_WORKSHOP_SN_ADMIN_PWD
- name: SE_WORKSHOP_GKE_GENERATOR
