#!/usr/bin/env python3

import os
import shutil
from pyharnessworkshop import harness, utils

# REQUIRED VARIABLES LIST
HARNESS_ACCOUNT_ID = os.getenv("SE_WORKSHOP_ACCOUNT_ID")
HARNESS_PAT = os.getenv("SE_WORKSHOP_PAT")
USER_EMAIL = utils.instruqt.get_agent_variable("HARNESS_USER")

# Remove workshop user from the TeamA group
harness.platform.remove_user_from_user_group(HARNESS_PAT, HARNESS_ACCOUNT_ID, USER_EMAIL, "TeamA")
