#!/usr/bin/env python3

# Standard library imports
import os
from pyharnessworkshop import harness, utils

# REQUIRED VARIABLES LIST
HARNESS_ACCOUNT_ID = os.getenv("SE_WORKSHOP_ACCOUNT_ID")
HARNESS_ORG_ID = os.getenv("SE_WORKSHOP_ORG_ID")
HARNESS_PAT = os.getenv("SE_WORKSHOP_PAT")
HARNESS_PROJECT = utils.instruqt.get_agent_variable("HARNESS_PRJ_ID")
USER_EMAIL = utils.instruqt.get_agent_variable("HARNESS_USER")
USER_EMAIL_CLEAN = USER_EMAIL.replace("@", "%40")
HARNESS_API = "https://app.harness.io"


user_id = harness.platform.get_harness_user_id(HARNESS_PAT, HARNESS_ACCOUNT_ID, USER_EMAIL_CLEAN)
users = [f"{user_id}"]
harness.platform.create_user_group(HARNESS_PAT, HARNESS_ACCOUNT_ID, HARNESS_ORG_ID, HARNESS_PROJECT, "Production Approvers", users)
